services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: always
    depends_on:
      - db
      # - benchmark-service

  # benchmark-service:
  #   build:
  #     context: benchmark-service
  #     dockerfile: Dockerfile
  #   env_file:
  #     - benchmark-service/.env

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql

  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - envoy
  #     - backend

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "9000:9000"
    volumes:
      - ./frontend/envoy_docker.yaml:/etc/envoy/envoy.yaml
