services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: host
    restart: always
    depends_on:
      - db
      - benchmark-service

  benchmark-service:
    build:
      context: benchmark-service
      dockerfile: Dockerfile
    network_mode: host

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./data:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    network_mode: host
    environment:
      - NGINX_PORT=80
    depends_on:
      - envoy
      - backend

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    network_mode: host
    volumes:
      - ./frontend/envoy_docker.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
