services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    network_mode: host
    depends_on:
      - db
      - benchmark-service
    volumes:
      - "./backend/storage:/app/storage"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  benchmark-service:
    build:
      context: benchmark-service
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: host
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./data:/var/lib/mysql
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NGINX_PORT=80
    network_mode: host
    depends_on:
      - envoy
      - backend
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    network_mode: host
    volumes:
      - ./frontend/envoy_docker.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
