services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - db
      - benchmark-service

  benchmark-service:
    build:
      context: benchmark-service
      dockerfile: Dockerfile
    depends_on:
      - redis

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 8000:80
    environment:
      - NGINX_PORT=80
    depends_on:
      - envoy
      - backend

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./frontend/envoy_docker.yaml:/etc/envoy/envoy.yaml

  redis:
    image: redis/redis-stack:7.0
    ports:
      - "6379:6379"
      - "8001:8001"
