apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yaml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/su-csexpa-benchmark-system-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: NGINX_PORT
              value: "80"
          image: {{ .Values.frontend.image }}
          name: frontend
          resources: {}
          ports:
            - containerPort: 80
      restartPolicy: Always
status: {}
