grpc_server:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
      - require_unimplemented_servers=false
      - module=github.com/ohkilab/SU-CSexpA-benchmark-system/proto-gen/go

client:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
      - module=github.com/ohkilab/SU-CSexpA-benchmark-system/proto-gen/go
  # grpc-web:
  #   plugin:
  #     name: protoc-gen-grpc-web
  #     path: ./bin/protoc-gen-grpc-web
  #   dist: import_style=typescript,mode=grpcwebtext:../proto-gen/web/src
  ts:
    plugin:
      name: protoc-gen-ts_proto
      path: ./node_modules/.bin/protoc-gen-ts_proto
    dist: ../proto-gen/web/src
    raw_options:
      "--proto_path": ./services