grpc_server:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
      - require_unimplemented_servers=false

client:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
  grpc-web:
    plugin:
      name: protoc-gen-grpc-web
      path: ./bin/protoc-gen-grpc-web
    dist: import_style=typescript,mode=grpcwebtext:../proto-gen/web/src
  ts:
    plugin:
      name: protoc-gen-ts_proto
      path: ./node_modules/.bin/protoc-gen-ts_proto
    dist: service=grpc-web:../proto-gen/web/src
