grpc_server:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
      - require_unimplemented_servers=false

client:
  go:
    dist: ../proto-gen/go
    opts:
      - paths=source_relative
